name: Example Workflow

on: [push]

jobs:
  set_env_var:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          echo "MY_ENV_VAR=HelloWorld" >> $GITHUB_ENV

  example_job:
    runs-on: ubuntu-latest
    needs:
      [
        set_env_var,
      ]    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Environment Variable
        run: echo "The value of MY_ENV_VAR is ${{ env.MY_ENV_VAR }}"

      - name: Use Environment Variable in Another Step
        run: |
          if [[ "${{ env.MY_ENV_VAR }}" == "HelloWorld" ]]; then
            echo "The environment variable is correctly set!"
          else
            echo "The environment variable is not set correctly."
          fi
